// The real recipe library.
//
// Transcribed from the recipe database in Drive — the seventy-eight files
// there that carry an actual ingredient list. The video bookmarks, the dead
// links, the pages that blocked a fetch and the pointer files that only say
// "see the other file" are not here, because there is nothing in them to
// itemise. Three files that do list ingredients are also absent: Bucatini
// all'Amatriciana has no ingredient section at all, and Grandma's Favorite
// Steak and Katsuobushi-Aged Steak name ingredients without a single quantity.
// Inventing amounts for those would have produced numbers with no source.
//
// FOUR THINGS THAT HAD TO BE DECIDED, AND ARE THEREFORE WRITTEN DOWN.
//
// 1. UNITS WERE CONVERTED, NOT REINTERPRETED. Cups, decilitres, ounces and
//    pounds became grams and millilitres at the conventional rates (1 cup =
//    240 ml, 1 dl = 100 ml, 1 oz = 28 g, 1 lb = 454 g). Where a source gave
//    both a volume and a weight, the weight won.
//
// 2. DEEP-FRYING OIL IS COUNTED AS ABSORBED, NOT AS BOUGHT. A recipe calling
//    for two litres of frying oil does not put two litres into the food, and
//    entering it that way would put eighteen thousand calories on a plate. The
//    lines here carry a plausible absorbed amount and say so in the notes. It
//    is the one place in this file where the shopping list is deliberately
//    wrong and the nutrition deliberately right.
//
// 3. "SALT TO TASTE" IS NOT A QUANTITY. Unmeasured seasoning was left out
//    rather than guessed at. Where a source quantified salt or pepper, it is
//    here; where it said "to season", the notes say so.
//
// 4. SERVINGS WERE FILLED IN WHERE THE SOURCE WAS SILENT. Roughly half these
//    recipes never state a yield. Those carry an estimate, which matters more
//    than it looks: servings is the divisor on every per-serving figure the
//    planner shows. A recipe whose macros look implausible is usually a
//    recipe whose serves is wrong, and that is one number to fix, in the
//    editor, without touching a line.
//
// Sauces, marinades and condiments have no `mealTypes`, so the auto-planner
// never offers chilli oil as a lunch. They are in the library to be cooked
// from and shopped for, not to be planned into a slot.

import type { Recipe } from './types';
import { allFoods, recipeMacros, ZERO_MACROS } from './foods';

/** Written without macros, which are computed from the food library below. */
type RecipeDraft = Omit<Recipe, 'macros'>;

const drafts: RecipeDraft[] = [
  // -------------------------------------------------------------------------
  // Aasialaiset
  // -------------------------------------------------------------------------
  {
    id: 'lib-mapo-tofu',
    name: 'Authentic Mapo Tofu',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 20,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'adamliaw.com/recipe/authentic-mapo-tofu\n\nServings not stated in the source; four is an estimate. Season with salt and sugar to taste before serving — doubanjiang brands vary a lot. Pork mince substitutes for beef.',
    lines: [
      { foodId: 'fd-tofu', qty: 600, unit: 'g' },
      { foodId: 'fd-beefmince', qty: 200, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-doubanjiang', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-blackbeansalted', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-chilipowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-springonion', qty: 6, unit: 'pcs' },
      { foodId: 'fd-cornstarch', qty: 1, unit: 'tsp' },
      { foodId: 'fd-sichuanpepper', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-banh-mi',
    name: 'Bánh Mì',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'hs.fi/ruoka/reseptit/a1397630068255\n\nThe pickle needs a couple of hours, or overnight. The filling can just as well be slow-braised pork, Vietnamese meatballs or spicy sausage instead of the chicken.',
    lines: [
      { foodId: 'fd-baguette', qty: 1, unit: 'pcs' },
      { foodId: 'fd-rotisserie', qty: 1, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 2, unit: 'pcs' },
      { foodId: 'fd-coriander', qty: 30, unit: 'g' },
      { foodId: 'fd-mayo', qty: 6, unit: 'tbsp' },
      { foodId: 'fd-sriracha', qty: 6, unit: 'tsp' },
      { foodId: 'fd-carrot', qty: 200, unit: 'g' },
      { foodId: 'fd-daikon', qty: 200, unit: 'g' },
      { foodId: 'fd-vinegar', qty: 150, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-cabbage-slaw',
    name: 'Cabbage Slaw',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 10,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=D6diqH8RF4U\n\nThe side that goes with the chicken katsu. Only ingredients were pasted from the video, no method — it is tossed together. Salt, lemon juice and a spicy chilli garlic topping go in to taste. A quarter head of cabbage taken here as 250 g.',
    lines: [
      { foodId: 'fd-cabbage', qty: 250, unit: 'g' },
      { foodId: 'fd-springonion', qty: 4, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-salt-pepper-pork-chops',
    name: 'Cantonese Salt and Pepper Pork Chops',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 3,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'woocancook.com/jiao-yan-zhu-pai\n\nThe source calls for 64 oz of frying oil plus 4 tbsp for the wok; the single oil line here is roughly what the batch absorbs plus the wok oil, not what you buy.',
    lines: [
      { foodId: 'fd-porkchop', qty: 450, unit: 'g' },
      { foodId: 'fd-jalapeno', qty: 2, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 8, unit: 'pcs' },
      { foodId: 'fd-cornstarch', qty: 60, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 115, unit: 'ml' },
      { foodId: 'fd-salt', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-whitepepper', qty: 0.5, unit: 'tbsp' },
      { foodId: 'fd-garlicpowder', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-onionpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-fivespice', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-soysauce', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-shaoxing', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-garlic-chili-noodles',
    name: 'Garlic Chili Noodles',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 20,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=bG8KpOvN5V8\n\nServings not stated; two is an estimate. The oyster sauce in the source is the plant-based kind.',
    lines: [
      { foodId: 'fd-tofu', qty: 100, unit: 'g' },
      { foodId: 'fd-garlic', qty: 5, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 10, unit: 'g' },
      { foodId: 'fd-springonion', qty: 3, unit: 'pcs' },
      { foodId: 'fd-vegoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-darksoy', qty: 3, unit: 'tsp' },
      { foodId: 'fd-wheatnoodle', qty: 150, unit: 'g' },
      { foodId: 'fd-chiliflakes', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-heo-kho-to',
    name: 'Heo Kho To, Vietnamese Braised Pork',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 150,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit/a1461117422174\n\nAbout two hours of simmering. Finished with halved boiled eggs, spring onion and red chilli.',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 800, unit: 'g' },
      { foodId: 'fd-shallot', qty: 6, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-lemongrass', qty: 2, unit: 'pcs' },
      { foodId: 'fd-rapeseedoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-butter', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-cornstarch', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-tomatopaste', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-brownsugar', qty: 45, unit: 'g' },
      { foodId: 'fd-soysauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-vinegar', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-worcestershire', qty: 8, unit: 'ml' },
      { foodId: 'fd-mustard', qty: 2, unit: 'tsp' },
      { foodId: 'fd-sriracha', qty: 1, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-staranise', qty: 2, unit: 'pcs' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-egg', qty: 2, unit: 'pcs' },
      { foodId: 'fd-springonion', qty: 2, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-red-braised-pork-belly',
    name: 'Home-style Red Braised Pork Belly',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 110,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'reddit.com/r/Cooking — 红烧肉, home-style method\n\nServings not stated; four is an estimate. The rock sugar goes in as two additions of 40 g. Water to reach halfway up the pork.',
    lines: [
      { foodId: 'fd-porkbelly', qty: 600, unit: 'g' },
      { foodId: 'fd-brownsugar', qty: 80, unit: 'g' },
      { foodId: 'fd-shaoxing', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-darksoy', qty: 60, unit: 'ml' },
      { foodId: 'fd-soysauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-ginger', qty: 25, unit: 'g' },
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-staranise', qty: 2, unit: 'pcs' },
      { foodId: 'fd-cinnamon', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-driedchili', qty: 2, unit: 'pcs' },
      { foodId: 'fd-sichuanpepper', qty: 12, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-sweet-sour-pork',
    name: 'Sweet and Sour Pork',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'adamliaw.com/recipe/how-to-make-sweet-and-sour-pork\n\nServings not stated; four is an estimate. The source deep-fries in about a litre of canola oil — the oil line here is what the batch absorbs, not what you buy.',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 500, unit: 'g' },
      { foodId: 'fd-soysauce', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-shaoxing', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-egg', qty: 1, unit: 'pcs' },
      { foodId: 'fd-cornstarch', qty: 62, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-carrot', qty: 1, unit: 'pcs' },
      { foodId: 'fd-bellpepper', qty: 1, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-cherrytomato', qty: 120, unit: 'g' },
      { foodId: 'fd-pineapple', qty: 150, unit: 'g' },
      { foodId: 'fd-chickenstock', qty: 60, unit: 'ml' },
      { foodId: 'fd-vinegar', qty: 60, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-ketchup', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-jang-kalguksu',
    name: 'Korean Gochujang Noodle Soup',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'aaronandclaire.com — jang kalguksu\n\nMinced garlic given as a tablespoon in the source, entered here as two cloves.',
    lines: [
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-zucchini', qty: 120, unit: 'g' },
      { foodId: 'fd-potato', qty: 120, unit: 'g' },
      { foodId: 'fd-shiitake', qty: 2, unit: 'pcs' },
      { foodId: 'fd-springonion', qty: 4, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-beefmince', qty: 150, unit: 'g' },
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-wheatnoodle', qty: 300, unit: 'g' },
      { foodId: 'fd-nori', qty: 2, unit: 'pcs' },
      { foodId: 'fd-sesameseed', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 9, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 1, unit: 'tsp' },
      { foodId: 'fd-gochujang', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-doenjang', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-chiliflakes', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-stockcube', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-msg', qty: 0.25, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-korean-beef-bowl',
    name: 'Korean Ground Beef Bowl',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 15,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit/art-2000008313654.html\n\nThe source says only "cooked basmati rice, minced spring onion, sesame seeds" to serve; the amounts for those three are estimates.',
    lines: [
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-rapeseedoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-beefmince', qty: 400, unit: 'g' },
      { foodId: 'fd-soysauce', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-brownsugar', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-sesameoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-gochujang', qty: 1, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-basmati', qty: 200, unit: 'g' },
      { foodId: 'fd-springonion', qty: 2, unit: 'pcs' },
      { foodId: 'fd-sesameseed', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-nasi-goreng',
    name: 'Nasi Goreng',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit — Paistettua riisiä, Nasi goreng\n\n3 dl of jasmine rice taken as 255 g dry. Topped with fresh coriander and a shredded two-egg omelette.',
    lines: [
      { foodId: 'fd-vegoil', qty: 6, unit: 'tbsp' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-springonion', qty: 5, unit: 'pcs' },
      { foodId: 'fd-cabbage', qty: 300, unit: 'g' },
      { foodId: 'fd-carrot', qty: 3, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
      { foodId: 'fd-chicken', qty: 250, unit: 'g' },
      { foodId: 'fd-porkshoulder', qty: 200, unit: 'g' },
      { foodId: 'fd-jasminerice', qty: 255, unit: 'g' },
      { foodId: 'fd-currypaste', qty: 2, unit: 'tsp' },
      { foodId: 'fd-whitepepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-chickenstock', qty: 700, unit: 'ml' },
      { foodId: 'fd-kecapmanis', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-sugar', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-prawns', qty: 100, unit: 'g' },
      { foodId: 'fd-coriander', qty: 20, unit: 'g' },
      { foodId: 'fd-egg', qty: 2, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-taco-rice',
    name: 'Okinawan Taco Rice',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'adamliaw.com/recipe/okinawan-taco-rice\n\n8 cups of cooked short-grain rice entered as 480 g dry, since everything in this planner is stated as bought. Taco seasoning can be a packet or 1 tsp onion powder, 1 tsp garlic powder, 1 tsp salt, 1 tbsp cumin, 1 tbsp smoked paprika and 2 tsp dried oregano.',
    lines: [
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-beefmince', qty: 500, unit: 'g' },
      { foodId: 'fd-tacoseasoning', qty: 1, unit: 'pcs' },
      { foodId: 'fd-soysauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-dashi', qty: 150, unit: 'ml' },
      { foodId: 'fd-sushirice', qty: 480, unit: 'g' },
      { foodId: 'fd-cheese', qty: 400, unit: 'g' },
      { foodId: 'fd-lettuce', qty: 420, unit: 'g' },
      { foodId: 'fd-tomato', qty: 2, unit: 'pcs' },
      { foodId: 'fd-salsa', qty: 240, unit: 'g' },
    ],
  },
  {
    id: 'lib-pan-fried-chicken-thighs',
    name: 'Pan-Fried Chicken Thighs',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'madewithlau.com/recipes/pan-fried-chicken-thighs\n\nCornflour line combines the 3 tbsp coating and the 2 tbsp in the marinade. Half a teaspoon of garlic salt entered as garlic powder.',
    lines: [
      { foodId: 'fd-chickenthigh', qty: 480, unit: 'g' },
      { foodId: 'fd-redonion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-cornstarch', qty: 5, unit: 'tbsp' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-shaoxing', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-sugar', qty: 1, unit: 'tsp' },
      { foodId: 'fd-whitepepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-ginger', qty: 14, unit: 'g' },
      { foodId: 'fd-garlicpowder', qty: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-karaage',
    name: 'Perfect Karaage Chicken',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 45,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=_FAyrvfQJi0\n\nThirty minutes marinating, ten cooking. Servings not stated; two is an estimate. Frying oil counted as absorbed, not as bought. Finished with a negishio topping of spring onion, sesame oil and salt.',
    lines: [
      { foodId: 'fd-chicken', qty: 300, unit: 'g' },
      { foodId: 'fd-ginger', qty: 25, unit: 'g' },
      { foodId: 'fd-garlic', qty: 1, unit: 'pcs' },
      { foodId: 'fd-sake', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-flour', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-potatostarch', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-vegoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-springonion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-sesameoil', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-prawn-noodles',
    name: 'Prawn Noodles',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 20,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=T60ppfnKxhs\n\nOne of four one-pan meals in the video. Ingredients and amounts were pasted from it; no method was given.',
    lines: [
      { foodId: 'fd-ricenoodle', qty: 175, unit: 'g' },
      { foodId: 'fd-prawns', qty: 190, unit: 'g' },
      { foodId: 'fd-bokchoy', qty: 100, unit: 'g' },
      { foodId: 'fd-sesameoil', qty: 15, unit: 'ml' },
      { foodId: 'fd-springonion', qty: 50, unit: 'g' },
      { foodId: 'fd-chili', qty: 2, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 10, unit: 'g' },
      { foodId: 'fd-soysauce', qty: 20, unit: 'ml' },
      { foodId: 'fd-vegoil', qty: 5, unit: 'ml' },
    ],
  },
  {
    id: 'lib-teriyaki-donburi',
    name: 'Red Wine Teriyaki Steak Donburi',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 20,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'adamliaw.com/recipe/red-wine-teriyaki-steak-donburi\n\nThe glaze is the Red Wine Teriyaki Sauce in this library; it is entered here as a generic teriyaki line, so make the sauce separately and the shopping list will not double-count it. Rice given as 3–5 cups cooked, entered as 200 g dry. Servings not stated; two is an estimate.',
    lines: [
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-vegoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-steak', qty: 400, unit: 'g' },
      { foodId: 'fd-sushirice', qty: 200, unit: 'g' },
      { foodId: 'fd-nori', qty: 1, unit: 'pcs' },
      { foodId: 'fd-wasabi', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-teriyaki', qty: 120, unit: 'ml' },
    ],
  },
  {
    id: 'lib-black-pepper-beef',
    name: 'Chinese Black Pepper Beef Stir Fry',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'schoolofwok.co.uk/tips-and-recipes/black-pepper-beef',
    lines: [
      { foodId: 'fd-steak', qty: 350, unit: 'g' },
      { foodId: 'fd-ginger', qty: 15, unit: 'g' },
      { foodId: 'fd-springonion', qty: 2, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-bellpepper', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-sesameoil', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cornstarch', qty: 1, unit: 'tsp' },
      { foodId: 'fd-blackpeppersauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-shaoxing', qty: 2, unit: 'tsp' },
      { foodId: 'fd-chickenstock', qty: 30, unit: 'ml' },
    ],
  },
  {
    id: 'lib-san-bei-ji',
    name: 'Taiwanese Three Cup Chicken',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 3,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'woocancook.com/san-bei-ji\n\nThree green onions, or a bunch of Thai basil instead. Tian Jin peppers entered as dried chillies.',
    lines: [
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-springonion', qty: 3, unit: 'pcs' },
      { foodId: 'fd-chickenthigh', qty: 450, unit: 'g' },
      { foodId: 'fd-driedchili', qty: 5, unit: 'pcs' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-sesameoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-shaoxing', qty: 60, unit: 'ml' },
      { foodId: 'fd-brownsugar', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-darksoy', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-beef-noodle-soup',
    name: 'Taiwanese Beef Noodle Soup',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 210,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'curatedkitchenware.com — Taiwanese beef noodle soup\n\nThree to four hours of simmering. Servings not stated; six is an estimate, and the noodles are entered as 400 g dry for six bowls rather than the source\'s "1 cup".',
    lines: [
      { foodId: 'fd-brisket', qty: 1000, unit: 'g' },
      { foodId: 'fd-shaoxing', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-ginger', qty: 35, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-sugar', qty: 1.5, unit: 'tbsp' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-springonion', qty: 3, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-cinnamon', qty: 1, unit: 'pcs' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-driedchili', qty: 3, unit: 'pcs' },
      { foodId: 'fd-staranise', qty: 2, unit: 'pcs' },
      { foodId: 'fd-driedorangepeel', qty: 2, unit: 'pcs' },
      { foodId: 'fd-doubanjiang', qty: 1.5, unit: 'tbsp' },
      { foodId: 'fd-tomatopaste', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 1.5, unit: 'tbsp' },
      { foodId: 'fd-darksoy', qty: 1, unit: 'tsp' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tbsp' },
      { foodId: 'fd-wheatnoodle', qty: 400, unit: 'g' },
      { foodId: 'fd-beefstock', qty: 120, unit: 'ml' },
      { foodId: 'fd-bokchoy', qty: 300, unit: 'g' },
    ],
  },
  {
    id: 'lib-butter-chicken-curry',
    name: 'Butter Chicken',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 90,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'joshuaweissman.com — the two dollar curry\n\nAn hour of marinating, half an hour of cooking. Turmeric is optional in the source. Served with steamed rice and coriander.',
    lines: [
      { foodId: 'fd-yoghurt', qty: 240, unit: 'g' },
      { foodId: 'fd-garammasala', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-chickenthigh', qty: 680, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 30, unit: 'g' },
      { foodId: 'fd-garlic', qty: 6, unit: 'pcs' },
      { foodId: 'fd-paprika', qty: 2, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 2, unit: 'tsp' },
      { foodId: 'fd-turmeric', qty: 1.5, unit: 'tsp' },
      { foodId: 'fd-crushedtomato', qty: 400, unit: 'g' },
      { foodId: 'fd-cream', qty: 240, unit: 'ml' },
      { foodId: 'fd-butter', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-basmati', qty: 200, unit: 'g' },
      { foodId: 'fd-coriander', qty: 15, unit: 'g' },
    ],
  },
  {
    id: 'lib-chicken-katsu',
    name: 'Chicken Katsu',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=D6diqH8RF4U\n\nGoes with the cabbage slaw and the tonkatsu sauce in this library. Salt or miso to taste — miso is very salty. The 2 cups of frying oil are counted here as what a batch absorbs, not as bought.',
    lines: [
      { foodId: 'fd-chicken', qty: 600, unit: 'g' },
      { foodId: 'fd-flour', qty: 290, unit: 'g' },
      { foodId: 'fd-egg', qty: 3, unit: 'pcs' },
      { foodId: 'fd-panko', qty: 210, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 80, unit: 'ml' },
    ],
  },
  {
    id: 'lib-tonkatsu-sauce',
    name: 'Tonkatsu Sauce',
    category: 'cat-asian',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 5,
    mealTypes: [],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=D6diqH8RF4U\n\nMakes roughly 90 ml, enough for four servings of katsu.',
    lines: [
      { foodId: 'fd-ketchup', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-worcestershire', qty: 14, unit: 'ml' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-miso', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-honey', qty: 1, unit: 'tsp' },
    ],
  },

  // -------------------------------------------------------------------------
  // General
  // -------------------------------------------------------------------------
  {
    id: 'lib-baked-chicken-fries',
    name: 'Baked Chicken Fries',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'tasty.co/recipe/baked-chicken-fries',
    lines: [
      { foodId: 'fd-chicken', qty: 600, unit: 'g' },
      { foodId: 'fd-breadcrumbs', qty: 230, unit: 'g' },
      { foodId: 'fd-flour', qty: 125, unit: 'g' },
      { foodId: 'fd-egg', qty: 5, unit: 'pcs' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlicpowder', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-onionpowder', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-driedbasil', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-driedoregano', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-tacos-campechanos',
    name: 'Beef and Chorizo Tacos',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'hs.fi/ruoka/reseptit — Naudanliha-chorizotacot, Tacos Campechanos\n\nOil, salt and pepper to taste; the oil line is an estimate.',
    lines: [
      { foodId: 'fd-tortilla', qty: 8, unit: 'pcs' },
      { foodId: 'fd-beefchuck', qty: 250, unit: 'g' },
      { foodId: 'fd-chorizo', qty: 250, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-coriander', qty: 20, unit: 'g' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-lime', qty: 2, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-bordelaise',
    name: 'Bordelaise Sauce',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: [],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=73hH87tmPZY\n\nThe source quantifies only the wine and the stock. The butter, shallots and bone marrow here are estimates — adjust them and the sauce follows.',
    lines: [
      { foodId: 'fd-butter', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-shallot', qty: 2, unit: 'pcs' },
      { foodId: 'fd-redwine', qty: 200, unit: 'ml' },
      { foodId: 'fd-beefstock', qty: 200, unit: 'ml' },
      { foodId: 'fd-bonemarrow', qty: 40, unit: 'g' },
    ],
  },
  {
    id: 'lib-burger-sauce',
    name: 'Burger Sauce',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 5,
    mealTypes: [],
    batchFriendly: true,
    notes: 'tasty.co/recipe/homemade-big-massive-burger\n\nThe source calls this enough for one burger. At 120 g of mayonnaise it is nearer four, which is what the servings say here.',
    lines: [
      { foodId: 'fd-mayo', qty: 120, unit: 'g' },
      { foodId: 'fd-gherkin', qty: 1, unit: 'pcs' },
      { foodId: 'fd-vinegar', qty: 1, unit: 'tsp' },
      { foodId: 'fd-mustard', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlicpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-onionpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 1, unit: 'tsp' },
      { foodId: 'fd-whitepepper', qty: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-garlic-mushrooms',
    name: 'Buttery Garlic Mushrooms',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 15,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'cafedelites.com/garlic-mushrooms\n\nThe onion and the white wine are optional in the source.',
    lines: [
      { foodId: 'fd-butter', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-oliveoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-mushroom', qty: 454, unit: 'g' },
      { foodId: 'fd-whitewine', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-thyme', qty: 1, unit: 'tsp' },
      { foodId: 'fd-parsley', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-chimichurri',
    name: 'Chimichurri Sauce',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 10,
    mealTypes: [],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=xvWrNpkk32Q\n\nA condiment, not a dish. Salt, sugar and chilli flakes to taste; the flake line is an estimate. Servings not stated; eight is an estimate.',
    lines: [
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-oreganofresh', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-dillfresh', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-mint', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-coriander', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-parsley', qty: 60, unit: 'g' },
      { foodId: 'fd-lemon', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-lemonjuice', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-oliveoil', qty: 120, unit: 'ml' },
      { foodId: 'fd-chiliflakes', qty: 1, unit: 'tsp' },
      { foodId: 'fd-vinegar', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-toum',
    name: 'Fluffy Lebanese Garlic Sauce, Toum',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 20,
    prepMinutes: 20,
    mealTypes: [],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=ifOlf3COK4s\n\nRests overnight. Servings not stated; twenty is an estimate for what is nearly a litre of emulsified oil, so the per-serving figure moves a lot if you disagree with it.',
    lines: [
      { foodId: 'fd-garlic', qty: 150, unit: 'g' },
      { foodId: 'fd-lemonjuice', qty: 135, unit: 'ml' },
      { foodId: 'fd-vegoil', qty: 600, unit: 'ml' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-jerk-chicken',
    name: 'Jamaican-Style Jerk Chicken with Bean Rice',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 180,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit/a1400041271067\n\nTwo hours marinating, about 55 minutes baking. Servings not stated; six is an estimate for 1.5 kg of chicken. The basting sauce is the leftover marinade with barbecue sauce and orange juice.',
    lines: [
      { foodId: 'fd-chickendrum', qty: 1500, unit: 'g' },
      { foodId: 'fd-onion', qty: 1.5, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 13, unit: 'pcs' },
      { foodId: 'fd-springonion', qty: 5, unit: 'pcs' },
      { foodId: 'fd-habanero', qty: 3, unit: 'pcs' },
      { foodId: 'fd-thyme', qty: 30, unit: 'g' },
      { foodId: 'fd-allspice', qty: 2.5, unit: 'tbsp' },
      { foodId: 'fd-brownsugar', qty: 25, unit: 'g' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tsp' },
      { foodId: 'fd-salt', qty: 2.5, unit: 'tsp' },
      { foodId: 'fd-nutmeg', qty: 1, unit: 'tsp' },
      { foodId: 'fd-soysauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-orangejuice', qty: 100, unit: 'ml' },
      { foodId: 'fd-bbqsauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-basmati', qty: 425, unit: 'g' },
      { foodId: 'fd-butter', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-kidneybeans', qty: 480, unit: 'g' },
      { foodId: 'fd-coconutmilk', qty: 400, unit: 'ml' },
    ],
  },
  {
    id: 'lib-middle-eastern-chilli-sauce',
    name: 'Middle Eastern Spicy Chilli Sauce',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 20,
    prepMinutes: 30,
    mealTypes: [],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=ifOlf3COK4s\n\nRefrigerated overnight. Cayenne peppers entered as fresh chilli. The extra tablespoon of ground cayenne is optional, for when the sauce comes out mild.',
    lines: [
      { foodId: 'fd-habanero', qty: 100, unit: 'g' },
      { foodId: 'fd-chili', qty: 200, unit: 'g' },
      { foodId: 'fd-bellpepper', qty: 300, unit: 'g' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-oliveoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-lemonjuice', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-vinegar', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-sugar', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-cayenne', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-garlicpowder', qty: 2, unit: 'tsp' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-groundcoriander', qty: 1, unit: 'tsp' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 0.25, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-peri-peri-jollof',
    name: 'Peri Peri Jollof Rice and Chicken',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 120,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'kikifoodies.com/recipes/peri-peri-jollof-rice-and-chicken\n\nTwo bulbs of garlic taken as 20 cloves, three cups of rice as 600 g dry. The peri peri sauce is made first and half a cup of it goes on the chicken.',
    lines: [
      { foodId: 'fd-chili', qty: 8, unit: 'pcs' },
      { foodId: 'fd-bellpepper', qty: 4, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 2.5, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 20, unit: 'pcs' },
      { foodId: 'fd-driedthyme', qty: 1, unit: 'tsp' },
      { foodId: 'fd-stockcube', qty: 2, unit: 'pcs' },
      { foodId: 'fd-sugar', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 2, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 2, unit: 'tsp' },
      { foodId: 'fd-lemonjuice', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-vegoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-chicken', qty: 1200, unit: 'g' },
      { foodId: 'fd-tomatopaste', qty: 115, unit: 'g' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-chickenstock', qty: 480, unit: 'ml' },
      { foodId: 'fd-whiterice', qty: 600, unit: 'g' },
      { foodId: 'fd-coriander', qty: 15, unit: 'g' },
    ],
  },
  {
    id: 'lib-red-wine-teriyaki-sauce',
    name: 'Red Wine Teriyaki Sauce',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 12,
    prepMinutes: 15,
    mealTypes: [],
    batchFriendly: true,
    notes: 'adamliaw.com/recipe/red-wine-teriyaki-steak-donburi\n\nMakes about 630 ml and keeps. Twelve servings of roughly 50 ml each.',
    lines: [
      { foodId: 'fd-soysauce', qty: 250, unit: 'ml' },
      { foodId: 'fd-redwine', qty: 200, unit: 'ml' },
      { foodId: 'fd-mirin', qty: 200, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 80, unit: 'g' },
    ],
  },
  {
    id: 'lib-sopa-de-ajo',
    name: 'Spanish Garlic Soup, Sopa de Ajo',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=fixHiTWKRWA\n\nSix cups of cubed bread taken as 200 g. Salt, pepper and cayenne to taste.',
    lines: [
      { foodId: 'fd-baguette', qty: 200, unit: 'g' },
      { foodId: 'fd-oliveoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-garlic', qty: 8, unit: 'pcs' },
      { foodId: 'fd-ham', qty: 57, unit: 'g' },
      { foodId: 'fd-paprika', qty: 2, unit: 'tsp' },
      { foodId: 'fd-chickenstock', qty: 1440, unit: 'ml' },
      { foodId: 'fd-egg', qty: 4, unit: 'pcs' },
      { foodId: 'fd-parsley', qty: 4, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-spicy-lime-dressing',
    name: 'Spicy Lime Dressing',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 5,
    mealTypes: [],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=1GMWn4IxVro\n\nJuice of one lime taken as 2 tbsp. Salt to taste. Servings not stated; four is an estimate.',
    lines: [
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-palmsugar', qty: 2, unit: 'tsp' },
      { foodId: 'fd-fishsauce', qty: 1, unit: 'tsp' },
      { foodId: 'fd-limejuice', qty: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-honey-soy-chicken-strips',
    name: 'Sweet and Sticky Honey Soy Chicken Strips',
    category: 'cat-general',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 45,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'whiteonricecouple.com — sticky honey garlic chicken strips\n\nThe chilli garlic sauce is optional in the source.',
    lines: [
      { foodId: 'fd-chicken', qty: 900, unit: 'g' },
      { foodId: 'fd-panko', qty: 60, unit: 'g' },
      { foodId: 'fd-egg', qty: 2, unit: 'pcs' },
      { foodId: 'fd-flour', qty: 95, unit: 'g' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-ketchup', qty: 120, unit: 'g' },
      { foodId: 'fd-honey', qty: 170, unit: 'g' },
      { foodId: 'fd-soysauce', qty: 60, unit: 'ml' },
      { foodId: 'fd-chiligarlic', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-limejuice', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-vinegar', qty: 1, unit: 'tbsp' },
    ],
  },

  // -------------------------------------------------------------------------
  // Haudutettavat
  // -------------------------------------------------------------------------
  {
    id: 'lib-baeckeoffe',
    name: 'Alsatian Meat Stew, Baeckeoffe',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 210,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit — Alsacen lihapata\n\nMarinates overnight, then two and a half to three hours in the oven. Servings not stated; six is an estimate for 900 g of meat. Half a bottle of an acidic white wine — Riesling or Silvaner — taken as 375 ml.',
    lines: [
      { foodId: 'fd-beefchuck', qty: 300, unit: 'g' },
      { foodId: 'fd-porkshoulder', qty: 300, unit: 'g' },
      { foodId: 'fd-lambshoulder', qty: 300, unit: 'g' },
      { foodId: 'fd-onion', qty: 4, unit: 'pcs' },
      { foodId: 'fd-leek', qty: 1, unit: 'pcs' },
      { foodId: 'fd-carrot', qty: 3, unit: 'pcs' },
      { foodId: 'fd-potato', qty: 1000, unit: 'g' },
      { foodId: 'fd-bayleaf', qty: 1, unit: 'pcs' },
      { foodId: 'fd-celery', qty: 45, unit: 'g' },
      { foodId: 'fd-garlic', qty: 1, unit: 'pcs' },
      { foodId: 'fd-thyme', qty: 10, unit: 'g' },
      { foodId: 'fd-whitewine', qty: 375, unit: 'ml' },
    ],
  },
  {
    id: 'lib-beef-bourguignon',
    name: 'Beef Bourguignon',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 195,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'cafedelites.com/beef-bourguignon — the Julia Child method\n\nThe onion line combines the large diced onion and the twelve pearl onions, which are optional in the source.',
    lines: [
      { foodId: 'fd-oliveoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-bacon', qty: 170, unit: 'g' },
      { foodId: 'fd-brisket', qty: 1360, unit: 'g' },
      { foodId: 'fd-carrot', qty: 1, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 230, unit: 'g' },
      { foodId: 'fd-garlic', qty: 6, unit: 'pcs' },
      { foodId: 'fd-flour', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-redwine', qty: 720, unit: 'ml' },
      { foodId: 'fd-beefstock', qty: 600, unit: 'ml' },
      { foodId: 'fd-tomatopaste', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-stockcube', qty: 1, unit: 'pcs' },
      { foodId: 'fd-thyme', qty: 1, unit: 'tsp' },
      { foodId: 'fd-parsley', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-mushroom', qty: 454, unit: 'g' },
      { foodId: 'fd-butter', qty: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-carnitas-orange-lime',
    name: 'Carnitas, Orange and Lime Braised',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 5,
    prepMinutes: 240,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'From the recipe database, adapted from an HS bonus recipe — no source URL recorded.\n\nTwo hours marinating, two or more hours braising, then finished in the oven.',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 800, unit: 'g' },
      { foodId: 'fd-lime', qty: 1, unit: 'pcs' },
      { foodId: 'fd-orange', qty: 1, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-driedoregano', qty: 1, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-chilipowder', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-bayleaf', qty: 1, unit: 'pcs' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-beefstock', qty: 500, unit: 'ml' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-chilli-con-jamie',
    name: 'Chilli con Jamie',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 10,
    prepMinutes: 250,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'jamieoliver.com/recipes/beef-recipes/chilli-con-jamie\n\nSoured cream is optional. Beans are two 400 g tins of whatever you like — kidney, butter or pinto.',
    lines: [
      { foodId: 'fd-brisket', qty: 2000, unit: 'g' },
      { foodId: 'fd-coffee', qty: 500, unit: 'ml' },
      { foodId: 'fd-driedchili', qty: 3, unit: 'pcs' },
      { foodId: 'fd-redonion', qty: 2, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 10, unit: 'pcs' },
      { foodId: 'fd-oliveoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-cumin', qty: 2, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 2, unit: 'tsp' },
      { foodId: 'fd-driedoregano', qty: 1, unit: 'tsp' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 4, unit: 'pcs' },
      { foodId: 'fd-cinnamon', qty: 2, unit: 'pcs' },
      { foodId: 'fd-crushedtomato', qty: 1600, unit: 'g' },
      { foodId: 'fd-molasses', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-bellpepper', qty: 3, unit: 'pcs' },
      { foodId: 'fd-kidneybeans', qty: 480, unit: 'g' },
      { foodId: 'fd-smetana', qty: 100, unit: 'g' },
    ],
  },
  {
    id: 'lib-coq-au-vin',
    name: 'Coq au Vin',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 200,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit/a1361374745276 — kukkoa viinissä, Donnie Brasco style\n\nMarinates overnight, then two to three hours in the oven. Servings not stated; six is an estimate for 1.5 kg of chicken. 3 dl of flour taken as 180 g.',
    lines: [
      { foodId: 'fd-chickendrum', qty: 1500, unit: 'g' },
      { foodId: 'fd-redwine', qty: 500, unit: 'ml' },
      { foodId: 'fd-passata', qty: 200, unit: 'ml' },
      { foodId: 'fd-driedthyme', qty: 1, unit: 'tsp' },
      { foodId: 'fd-bayleaf', qty: 1, unit: 'pcs' },
      { foodId: 'fd-carrot', qty: 3, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 3, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 1, unit: 'pcs' },
      { foodId: 'fd-flour', qty: 180, unit: 'g' },
      { foodId: 'fd-oliveoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-cognac', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-bacon', qty: 70, unit: 'g' },
    ],
  },
  {
    id: 'lib-jambalaya',
    name: 'Cajun Jambalaya',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 120,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'vice.com — easy jambalaya with Isaac Toups\n\nThe oil line is the half cup for the roux plus the two tablespoons for the pot.',
    lines: [
      { foodId: 'fd-chickendrum', qty: 454, unit: 'g' },
      { foodId: 'fd-salt', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-vegoil', qty: 150, unit: 'ml' },
      { foodId: 'fd-flour', qty: 60, unit: 'g' },
      { foodId: 'fd-celery', qty: 2, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-bellpepper', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 8, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
      { foodId: 'fd-chickenstock', qty: 1440, unit: 'ml' },
      { foodId: 'fd-sausage', qty: 454, unit: 'g' },
      { foodId: 'fd-whiterice', qty: 370, unit: 'g' },
      { foodId: 'fd-butter', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-springonion', qty: 6, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-lamb-shanks',
    name: 'Spicy Lamb Shanks',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 195,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'gordonramsayrecipes.uk — lamb shanks\n\nThe chilli line is the green and red chillies together. A whole 750 ml bottle of red wine, something like a basic Côtes du Rhône.',
    lines: [
      { foodId: 'fd-chili', qty: 3, unit: 'pcs' },
      { foodId: 'fd-paprika', qty: 2, unit: 'tsp' },
      { foodId: 'fd-driedoregano', qty: 2, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cinnamon', qty: 2, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-oliveoil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-lambshank', qty: 4, unit: 'pcs' },
      { foodId: 'fd-carrot', qty: 2, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-redwine', qty: 750, unit: 'ml' },
      { foodId: 'fd-chickenstock', qty: 500, unit: 'ml' },
      { foodId: 'fd-mint', qty: 10, unit: 'g' },
    ],
  },
  {
    id: 'lib-osso-buco',
    name: 'Osso Buco',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 300,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'bondiharvest.com/how-to-make-osso-buco\n\nMarinates overnight, then four hours in the oven. The stock is given as 2–3 litres; two is entered here.',
    lines: [
      { foodId: 'fd-vealshank', qty: 500, unit: 'g' },
      { foodId: 'fd-redwine', qty: 750, unit: 'ml' },
      { foodId: 'fd-beefstock', qty: 2000, unit: 'ml' },
      { foodId: 'fd-rosemary', qty: 15, unit: 'g' },
      { foodId: 'fd-thyme', qty: 15, unit: 'g' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-celery', qty: 60, unit: 'g' },
      { foodId: 'fd-carrot', qty: 60, unit: 'g' },
      { foodId: 'fd-tomato', qty: 6, unit: 'pcs' },
      { foodId: 'fd-tomatopaste', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-oliveoil', qty: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-milk-braised-carnitas',
    name: 'Orange and Milk Braised Pork Carnitas',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 240,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'foodwishes.blogspot.com — orange milk braised pork carnitas',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 1590, unit: 'g' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-cumin', qty: 2, unit: 'tsp' },
      { foodId: 'fd-driedoregano', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cayenne', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-orangejuice', qty: 120, unit: 'ml' },
      { foodId: 'fd-orange', qty: 1, unit: 'pcs' },
      { foodId: 'fd-wholemilk', qty: 480, unit: 'ml' },
    ],
  },
  {
    id: 'lib-perfect-pork-belly',
    name: 'Perfect Pork Belly',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 300,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'jamieoliver.com/recipes/pork/perfect-pork-belly\n\nDries uncovered overnight, then three to five hours. Four kilos of belly, bone in. Coriander seeds entered as ground coriander.',
    lines: [
      { foodId: 'fd-porkbelly', qty: 4000, unit: 'g' },
      { foodId: 'fd-bayleaf', qty: 6, unit: 'pcs' },
      { foodId: 'fd-salt', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-groundcoriander', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-fennelseed', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-blackpepper', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-onion', qty: 4, unit: 'pcs' },
      { foodId: 'fd-cider', qty: 300, unit: 'ml' },
      { foodId: 'fd-flour', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-carrot', qty: 4, unit: 'pcs' },
      { foodId: 'fd-potato', qty: 600, unit: 'g' },
      { foodId: 'fd-celery', qty: 4, unit: 'pcs' },
      { foodId: 'fd-fennelbulb', qty: 2, unit: 'pcs' },
      { foodId: 'fd-rosemary', qty: 4, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 12, unit: 'pcs' },
    ],
  },
  {
    id: 'lib-roasted-tomato-soup',
    name: 'Roasted Tomato Soup',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 70,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=qK15KwDBNBU\n\nServings not stated; six is an estimate for 1.5 kg of tomatoes. Three small snack peppers taken as 150 g. The cream is optional.',
    lines: [
      { foodId: 'fd-cherrytomato', qty: 1500, unit: 'g' },
      { foodId: 'fd-redonion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-bellpepper', qty: 150, unit: 'g' },
      { foodId: 'fd-garlic', qty: 10, unit: 'pcs' },
      { foodId: 'fd-rosemary', qty: 2, unit: 'pcs' },
      { foodId: 'fd-thyme', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-oliveoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-butter', qty: 30, unit: 'g' },
      { foodId: 'fd-tomatopaste', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-vegstock', qty: 660, unit: 'ml' },
      { foodId: 'fd-driedoregano', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-paprika', qty: 1, unit: 'tsp' },
      { foodId: 'fd-balsamic', qty: 0.5, unit: 'tbsp' },
      { foodId: 'fd-worcestershire', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-sugar', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-basil', qty: 15, unit: 'g' },
      { foodId: 'fd-cream', qty: 120, unit: 'ml' },
    ],
  },
  {
    id: 'lib-pulled-pork',
    name: 'Very Tender Pulled Pork Shoulder',
    category: 'cat-braise',
    macroSource: 'derived',
    serves: 10,
    prepMinutes: 900,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'hs.fi/ruoka/reseptit — ylikypsää possua\n\nTwo hours marinating, then thirteen to sixteen hours in the oven. Servings not stated; ten is an estimate for 2 kg of shoulder. 1 dl of muscovado taken as 90 g.',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 2000, unit: 'g' },
      { foodId: 'fd-jalapeno', qty: 3, unit: 'pcs' },
      { foodId: 'fd-chili', qty: 2, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-brownsugar', qty: 90, unit: 'g' },
      { foodId: 'fd-maplesyrup', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-ginger', qty: 20, unit: 'g' },
      { foodId: 'fd-groundginger', qty: 2, unit: 'tsp' },
      { foodId: 'fd-fennelseed', qty: 1, unit: 'tsp' },
      { foodId: 'fd-driedthyme', qty: 2, unit: 'tsp' },
      { foodId: 'fd-rapeseedoil', qty: 50, unit: 'ml' },
      { foodId: 'fd-beer', qty: 200, unit: 'ml' },
    ],
  },

  // -------------------------------------------------------------------------
  // Pastat
  // -------------------------------------------------------------------------
  {
    id: 'lib-bacon-mushroom-pasta',
    name: 'Bacon Mushroom Pasta',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 3,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=T60ppfnKxhs\n\nOne of four one-pan meals in the video. Ingredients and amounts were pasted from it; no method was given.',
    lines: [
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-butter', qty: 10, unit: 'g' },
      { foodId: 'fd-bacon', qty: 100, unit: 'g' },
      { foodId: 'fd-pasta', qty: 300, unit: 'g' },
      { foodId: 'fd-mushroom', qty: 100, unit: 'g' },
      { foodId: 'fd-singlecream', qty: 125, unit: 'ml' },
      { foodId: 'fd-parmesan', qty: 15, unit: 'g' },
      { foodId: 'fd-basil', qty: 5, unit: 'g' },
    ],
  },
  {
    id: 'lib-cacio-e-pepe',
    name: 'Cacio e Pepe, the New Way',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 20,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=zWVD5fGh48E\n\nThe source gives no weight for the Parmigiano; 60 g is an estimate. Parsley is optional.',
    lines: [
      { foodId: 'fd-oliveoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-butter', qty: 40, unit: 'g' },
      { foodId: 'fd-pasta', qty: 200, unit: 'g' },
      { foodId: 'fd-parmesan', qty: 60, unit: 'g' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-parsley', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-cherry-tomato-butter-pasta',
    name: 'Fettuccine with Cherry Tomato Butter Sauce',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'sipandfeast.com/fettuccine-cherry-tomato-butter-sauce',
    lines: [
      { foodId: 'fd-pasta', qty: 454, unit: 'g' },
      { foodId: 'fd-butter', qty: 113, unit: 'g' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-cherrytomato', qty: 1020, unit: 'g' },
      { foodId: 'fd-parsley', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-basil', qty: 10, unit: 'g' },
    ],
  },
  {
    id: 'lib-meatball-chorizo-orzo',
    name: 'Meatball Chorizo Orzo',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'youtube.com/watch?v=T60ppfnKxhs\n\nOne of four one-pan meals in the video. Ingredients and amounts were pasted from it; no method was given.',
    lines: [
      { foodId: 'fd-onion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-butter', qty: 10, unit: 'g' },
      { foodId: 'fd-meatballs', qty: 340, unit: 'g' },
      { foodId: 'fd-chickenstock', qty: 500, unit: 'ml' },
      { foodId: 'fd-crushedtomato', qty: 400, unit: 'g' },
      { foodId: 'fd-chorizo', qty: 30, unit: 'g' },
      { foodId: 'fd-cherrytomato', qty: 200, unit: 'g' },
      { foodId: 'fd-orzo', qty: 400, unit: 'g' },
      { foodId: 'fd-driedoregano', qty: 1, unit: 'tsp' },
      { foodId: 'fd-parsley', qty: 5, unit: 'g' },
    ],
  },
  {
    id: 'lib-pasta-alla-norcina',
    name: 'Pasta alla Norcina',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'sipandfeast.com/pasta-alla-norcina\n\nSix servings, or four very large ones.',
    lines: [
      { foodId: 'fd-pasta', qty: 454, unit: 'g' },
      { foodId: 'fd-mushroom', qty: 227, unit: 'g' },
      { foodId: 'fd-italiansausage', qty: 454, unit: 'g' },
      { foodId: 'fd-oliveoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-onion', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-whitewine', qty: 120, unit: 'ml' },
      { foodId: 'fd-cream', qty: 360, unit: 'ml' },
      { foodId: 'fd-nutmeg', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-pecorino', qty: 75, unit: 'g' },
    ],
  },
  {
    id: 'lib-cherry-tomato-pasta',
    name: 'Pasta with Cherry Tomato Sauce',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=7zS5Wj7ZfIY\n\nServings not stated; four is an estimate for a pound of pasta. Parmesan for serving, amount not given.',
    lines: [
      { foodId: 'fd-pasta', qty: 454, unit: 'g' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-oliveoil', qty: 90, unit: 'ml' },
      { foodId: 'fd-cherrytomato', qty: 750, unit: 'g' },
      { foodId: 'fd-basil', qty: 30, unit: 'g' },
      { foodId: 'fd-parmesan', qty: 30, unit: 'g' },
    ],
  },
  {
    id: 'lib-rigatoni-al-segreto',
    name: 'Rigatoni al Segreto',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/watch?v=o1xg1ntqSHU\n\nFour small servings or two large. The red pepper flakes are not in the original.',
    lines: [
      { foodId: 'fd-oliveoil', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-onion', qty: 150, unit: 'g' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-chiliflakes', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-crushedtomato', qty: 795, unit: 'g' },
      { foodId: 'fd-basil', qty: 10, unit: 'g' },
      { foodId: 'fd-parmesan', qty: 45, unit: 'g' },
      { foodId: 'fd-butter', qty: 4, unit: 'tbsp' },
      { foodId: 'fd-pasta', qty: 227, unit: 'g' },
    ],
  },
  {
    id: 'lib-chili-oil-vodka-pasta',
    name: 'Spicy Chili Oil Vodka Pasta',
    category: 'cat-pasta',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 30,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/shorts/8-XsUB5zFlY\n\nServings not stated; four is an estimate for a pound of rigatoni. The source gives no weight for the Parmigiano; 50 g is an estimate.',
    lines: [
      { foodId: 'fd-pancetta', qty: 80, unit: 'g' },
      { foodId: 'fd-chilioil', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-shallot', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-tomatopaste', qty: 180, unit: 'g' },
      { foodId: 'fd-vodka', qty: 60, unit: 'ml' },
      { foodId: 'fd-cream', qty: 360, unit: 'ml' },
      { foodId: 'fd-pasta', qty: 454, unit: 'g' },
      { foodId: 'fd-parmesan', qty: 50, unit: 'g' },
      { foodId: 'fd-butter', qty: 5, unit: 'tbsp' },
      { foodId: 'fd-basil', qty: 15, unit: 'g' },
    ],
  },

  // -------------------------------------------------------------------------
  // Pihvit ja muut lihat
  // -------------------------------------------------------------------------
  {
    id: 'lib-steak-au-poivre',
    name: 'Bistro Pepper Steak',
    category: 'cat-meat',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'thefrenchcookingacademy.com/recipes/pepper-steak\n\nMultiply for more, but cook in batches of two. Cream given as 50–100 ml; 75 is entered.',
    lines: [
      { foodId: 'fd-steak', qty: 400, unit: 'g' },
      { foodId: 'fd-oliveoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-shallot', qty: 1, unit: 'pcs' },
      { foodId: 'fd-butter', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-whitewine', qty: 100, unit: 'ml' },
      { foodId: 'fd-cognac', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-blackpepper', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-cream', qty: 75, unit: 'ml' },
      { foodId: 'fd-beefstock', qty: 100, unit: 'ml' },
    ],
  },
  {
    id: 'lib-cajun-pork-chops',
    name: 'Cajun-Spiced Pork Chops',
    category: 'cat-meat',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'hs.fi/ruoka/reseptit — Cajunmaustetut possuleikkeet\n\nThirty minutes marinating, then a few minutes in the pan.',
    lines: [
      { foodId: 'fd-porkchop', qty: 400, unit: 'g' },
      { foodId: 'fd-oliveoil', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 1, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-chilipowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-driedthyme', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-cayenne', qty: 0.25, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-grilled-chicken-deluxe',
    name: 'Grilled Chicken Deluxe Sandwich',
    category: 'cat-meat',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 35,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'cookwell.com — Chick-Fil-A style grilled chicken deluxe\n\nThe mayonnaise line combines the spoonful in the chicken marinade and the 20 g in the honey mustard barbecue sauce. Lettuce, tomato and pickled onion are "as needed" in the source; the amounts here are estimates.',
    lines: [
      { foodId: 'fd-chicken', qty: 300, unit: 'g' },
      { foodId: 'fd-garlic', qty: 1, unit: 'pcs' },
      { foodId: 'fd-lemon', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-mayo', qty: 35, unit: 'g' },
      { foodId: 'fd-driedthyme', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-briochebun', qty: 2, unit: 'pcs' },
      { foodId: 'fd-bacon', qty: 60, unit: 'g' },
      { foodId: 'fd-slicedcheese', qty: 2, unit: 'pcs' },
      { foodId: 'fd-lettuce', qty: 40, unit: 'g' },
      { foodId: 'fd-tomato', qty: 1, unit: 'pcs' },
      { foodId: 'fd-pickledonion', qty: 30, unit: 'g' },
      { foodId: 'fd-bbqsauce', qty: 20, unit: 'g' },
      { foodId: 'fd-honey', qty: 10, unit: 'g' },
      { foodId: 'fd-mustard', qty: 10, unit: 'g' },
    ],
  },
  {
    id: 'lib-crispy-carnitas',
    name: 'Crispy Pork Carnitas',
    category: 'cat-meat',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 240,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'foodwishes.blogspot.com — crispy pork carnitas\n\nAbout three and a half hours roasting, plus the crisping.',
    lines: [
      { foodId: 'fd-porkshoulder', qty: 1360, unit: 'g' },
      { foodId: 'fd-salt', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cinnamon', qty: 0.75, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-fivespice', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-orange', qty: 1, unit: 'pcs' },
      { foodId: 'fd-garlic', qty: 8, unit: 'pcs' },
      { foodId: 'fd-bayleaf', qty: 2, unit: 'pcs' },
      { foodId: 'fd-oliveoil', qty: 60, unit: 'ml' },
    ],
  },

  // -------------------------------------------------------------------------
  // Preppaus
  // -------------------------------------------------------------------------
  {
    id: 'lib-bbq-sauce',
    name: 'All-American Barbecue Sauce',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 16,
    prepMinutes: 20,
    mealTypes: [],
    batchFriendly: true,
    notes: 'allrecipes.com/recipe/280637/all-american-barbecue-sauce\n\nServings not stated; sixteen is an estimate for what two cups of ketchup makes.',
    lines: [
      { foodId: 'fd-ketchup', qty: 480, unit: 'g' },
      { foodId: 'fd-vinegar', qty: 120, unit: 'ml' },
      { foodId: 'fd-brownsugar', qty: 75, unit: 'g' },
      { foodId: 'fd-molasses', qty: 80, unit: 'g' },
      { foodId: 'fd-paprika', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-chilipowder', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-cayenne', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-allspice', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-groundcoriander', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 0.25, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-buffalo-tenders',
    name: 'Buffalo Chicken Tenders',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'youtube.com/shorts/kkQY2fERtAs\n\nTwelve minutes in an air fryer, twenty-five in an oven. Salt and pepper to taste.',
    lines: [
      { foodId: 'fd-chicken', qty: 680, unit: 'g' },
      { foodId: 'fd-egg', qty: 1, unit: 'pcs' },
      { foodId: 'fd-cornflakes', qty: 25, unit: 'g' },
      { foodId: 'fd-oatflour', qty: 30, unit: 'g' },
      { foodId: 'fd-garlicpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-onionpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-greekyog', qty: 113, unit: 'g' },
      { foodId: 'fd-lightmayo', qty: 30, unit: 'g' },
      { foodId: 'fd-sweetchilli', qty: 32, unit: 'g' },
      { foodId: 'fd-sriracha', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-butter-chicken-wrap',
    name: 'Butter Chicken Snack Wrap',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 60,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'cookwell.com — butter chicken wrap\n\nThe garam masala, fenugreek and Kashmiri chilli lines fold the "sprinkles" in the marinade and the garnish into the measured amounts. Lavash or naan; red onion and coriander to finish.',
    lines: [
      { foodId: 'fd-chicken', qty: 500, unit: 'g' },
      { foodId: 'fd-yoghurt', qty: 30, unit: 'g' },
      { foodId: 'fd-salt', qty: 1, unit: 'tsp' },
      { foodId: 'fd-chilipowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garammasala', qty: 2, unit: 'tsp' },
      { foodId: 'fd-crushedtomato', qty: 800, unit: 'g' },
      { foodId: 'fd-butter', qty: 60, unit: 'g' },
      { foodId: 'fd-turmeric', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-fenugreek', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-ginger', qty: 15, unit: 'g' },
      { foodId: 'fd-shallot', qty: 1, unit: 'pcs' },
      { foodId: 'fd-jalapeno', qty: 1, unit: 'pcs' },
      { foodId: 'fd-peanutbutter', qty: 15, unit: 'g' },
      { foodId: 'fd-cream', qty: 30, unit: 'ml' },
      { foodId: 'fd-lavash', qty: 4, unit: 'pcs' },
      { foodId: 'fd-redonion', qty: 0.5, unit: 'pcs' },
      { foodId: 'fd-coriander', qty: 10, unit: 'g' },
    ],
  },
  {
    id: 'lib-crispy-chilli-beef',
    name: 'Crispy Chilli Beef',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 3,
    prepMinutes: 45,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'cookwell.com — crispy chilli beef\n\nThe soy line combines the splash in the marinade and the 20 g in the sauce. Frying oil counted as absorbed, not as bought. Served with rice and coriander.',
    lines: [
      { foodId: 'fd-steak', qty: 400, unit: 'g' },
      { foodId: 'fd-egg', qty: 1, unit: 'pcs' },
      { foodId: 'fd-cornstarch', qty: 40, unit: 'g' },
      { foodId: 'fd-sesameoil', qty: 10, unit: 'ml' },
      { foodId: 'fd-soysauce', qty: 25, unit: 'ml' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-whitepepper', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-msg', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-vegoil', qty: 60, unit: 'ml' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 15, unit: 'g' },
      { foodId: 'fd-chili', qty: 1, unit: 'pcs' },
      { foodId: 'fd-ketchup', qty: 50, unit: 'g' },
      { foodId: 'fd-vinegar', qty: 50, unit: 'ml' },
      { foodId: 'fd-honey', qty: 50, unit: 'g' },
      { foodId: 'fd-darksoy', qty: 10, unit: 'ml' },
      { foodId: 'fd-whiterice', qty: 200, unit: 'g' },
      { foodId: 'fd-coriander', qty: 10, unit: 'g' },
      { foodId: 'fd-chiliflakes', qty: 1, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-chocolate-crumb',
    name: 'Crystallised Chocolate Crumb',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 10,
    prepMinutes: 20,
    mealTypes: ['snack'],
    batchFriendly: true,
    notes: 'dessertisans.com/recipe/crystallised-chocolate-crumb\n\nThe 90 g of water is not a line here — it boils off. Servings not stated; ten is an estimate.',
    lines: [
      { foodId: 'fd-sugar', qty: 240, unit: 'g' },
      { foodId: 'fd-darkchocolate', qty: 110, unit: 'g' },
    ],
  },
  {
    id: 'lib-fish-sauce-wings',
    name: 'Fish Sauce Wings',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 40,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/shorts/UP2l-NHCVSs\n\nThe fish sauce line is the 3 tbsp in the marinade plus the 3 tbsp in the topping. The oil line is the quarter cup in the topping plus what the frying absorbs.',
    lines: [
      { foodId: 'fd-chickenwing', qty: 900, unit: 'g' },
      { foodId: 'fd-fishsauce', qty: 6, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-msg', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tsp' },
      { foodId: 'fd-garlicpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-onionpowder', qty: 1, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 1, unit: 'tsp' },
      { foodId: 'fd-cornstarch', qty: 60, unit: 'g' },
      { foodId: 'fd-riceflour', qty: 60, unit: 'g' },
      { foodId: 'fd-bakingpowder', qty: 0.25, unit: 'tsp' },
      { foodId: 'fd-garlic', qty: 60, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 120, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 50, unit: 'g' },
      { foodId: 'fd-chili', qty: 4, unit: 'pcs' },
      { foodId: 'fd-limejuice', qty: 4, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-garlic-steak-stir-fry',
    name: 'Garlic Steak Stir Fry',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 2,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'iamneverfull.com/garlic-steak-stir-fry\n\nRice is optional in the source; 150 g dry is entered for two.',
    lines: [
      { foodId: 'fd-steak', qty: 454, unit: 'g' },
      { foodId: 'fd-shaoxing', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-cornstarch', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-garlic', qty: 11, unit: 'pcs' },
      { foodId: 'fd-darksoy', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-soysauce', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-oystersauce', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-sugar', qty: 2, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 1, unit: 'tsp' },
      { foodId: 'fd-whiterice', qty: 150, unit: 'g' },
    ],
  },
  {
    id: 'lib-harissa-wrap',
    name: 'High Protein Harissa Spiced Wrap',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 10,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'cookwell.com — high protein harissa spiced wrap\n\nGround meat unspecified in the source; entered as beef mince. Pickled cabbage, yoghurt, dill and pepper are all "to taste" — the amounts here are estimates.',
    lines: [
      { foodId: 'fd-beefmince', qty: 450, unit: 'g' },
      { foodId: 'fd-harissa', qty: 50, unit: 'g' },
      { foodId: 'fd-salt', qty: 4, unit: 'g' },
      { foodId: 'fd-cumin', qty: 1, unit: 'tsp' },
      { foodId: 'fd-lavash', qty: 4, unit: 'pcs' },
      { foodId: 'fd-pickledcabbage', qty: 100, unit: 'g' },
      { foodId: 'fd-yoghurt', qty: 100, unit: 'g' },
      { foodId: 'fd-drieddill', qty: 1, unit: 'tsp' },
      { foodId: 'fd-blackpepper', qty: 0.5, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-teriyaki-sauce',
    name: 'Homemade Teriyaki Sauce',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 12,
    prepMinutes: 5,
    mealTypes: [],
    batchFriendly: true,
    notes: 'adamliaw.com/recipe/homemade-teriyaki-sauce\n\nSugar given as 60–90 g; 75 is entered. Servings not stated; twelve is an estimate for the roughly 650 ml this makes.',
    lines: [
      { foodId: 'fd-soysauce', qty: 250, unit: 'ml' },
      { foodId: 'fd-mirin', qty: 200, unit: 'ml' },
      { foodId: 'fd-sake', qty: 200, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 75, unit: 'g' },
    ],
  },
  {
    id: 'lib-korean-wine-marinade',
    name: 'Korean Wine Marinade',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 10,
    mealTypes: [],
    batchFriendly: true,
    notes: 'toastmag.co.nz/recipe/korean-wine-marinade\n\nEnough for a kilogram of meat, which is taken here as eight servings. Black pepper to taste. A nashi pear is preferred.',
    lines: [
      { foodId: 'fd-whitewine', qty: 80, unit: 'ml' },
      { foodId: 'fd-pear', qty: 1, unit: 'pcs' },
      { foodId: 'fd-darksoy', qty: 240, unit: 'ml' },
      { foodId: 'fd-garlic', qty: 4, unit: 'pcs' },
      { foodId: 'fd-ginger', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-sesameoil', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-moms-chili-oil',
    name: "Mom's Chili Oil",
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 48,
    prepMinutes: 30,
    mealTypes: [],
    batchFriendly: true,
    notes: 'chawjcreations.com/moms-chili-oil\n\nMakes three or four 16 oz jars; forty-eight servings of roughly a tablespoon each. The chilli flake line is the Thai flakes and the coarse Korean flakes together. Here the oil really is bought in the quantity listed — this one is oil.',
    lines: [
      { foodId: 'fd-garlic', qty: 112, unit: 'g' },
      { foodId: 'fd-shallot', qty: 93, unit: 'g' },
      { foodId: 'fd-lemongrass', qty: 120, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 950, unit: 'ml' },
      { foodId: 'fd-chiliflakes', qty: 120, unit: 'g' },
      { foodId: 'fd-salt', qty: 22, unit: 'g' },
      { foodId: 'fd-stockcube', qty: 9, unit: 'g' },
      { foodId: 'fd-sichuanpepper', qty: 4, unit: 'g' },
    ],
  },
  {
    id: 'lib-prik-nam-pla',
    name: 'Prik Nam Pla',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 6,
    prepMinutes: 10,
    mealTypes: [],
    batchFriendly: false,
    notes: 'hot-thai-kitchen.com/prik-nam-pla\n\nBetter for ten minutes of infusion. Garlic and shallots are optional in the source. Servings not stated; six is an estimate.',
    lines: [
      { foodId: 'fd-chili', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-fishsauce', qty: 3, unit: 'tbsp' },
      { foodId: 'fd-limejuice', qty: 1, unit: 'tbsp' },
      { foodId: 'fd-garlic', qty: 2, unit: 'pcs' },
      { foodId: 'fd-shallot', qty: 2, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-roast-potatoes',
    name: 'The Best Roast Potatoes Ever',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 8,
    prepMinutes: 90,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: true,
    notes: 'seriouseats.com/the-best-roast-potatoes-ever-recipe\n\nServings not stated; eight is an estimate for 2 kg of potatoes. The fat can be olive oil, duck fat, goose fat or beef fat — olive oil is what is entered.',
    lines: [
      { foodId: 'fd-potato', qty: 2000, unit: 'g' },
      { foodId: 'fd-bakingsoda', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-oliveoil', qty: 75, unit: 'ml' },
      { foodId: 'fd-rosemary', qty: 5, unit: 'g' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-parsley', qty: 5, unit: 'g' },
      { foodId: 'fd-salt', qty: 2, unit: 'tsp' },
    ],
  },
  {
    id: 'lib-dads-chili-oil',
    name: "Dad's Chili Oil",
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 20,
    prepMinutes: 15,
    mealTypes: [],
    batchFriendly: true,
    notes: 'madewithlau.com/recipes/homemade-chili-oil — 辣椒油\n\nThe neutral oil line is the 4 oz for the infusion plus the tablespoon in the chilli mix.',
    lines: [
      { foodId: 'fd-chiliflakes', qty: 42, unit: 'g' },
      { foodId: 'fd-ginger', qty: 14, unit: 'g' },
      { foodId: 'fd-redonion', qty: 28, unit: 'g' },
      { foodId: 'fd-shallot', qty: 28, unit: 'g' },
      { foodId: 'fd-garlic', qty: 3, unit: 'pcs' },
      { foodId: 'fd-staranise', qty: 2, unit: 'pcs' },
      { foodId: 'fd-sesameseed', qty: 1, unit: 'tsp' },
      { foodId: 'fd-vegoil', qty: 127, unit: 'ml' },
      { foodId: 'fd-sesameoil', qty: 1, unit: 'tsp' },
      { foodId: 'fd-salt', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-sugar', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-whitepepper', qty: 0.5, unit: 'tsp' },
      { foodId: 'fd-paprika', qty: 1, unit: 'tbsp' },
    ],
  },
  {
    id: 'lib-pad-kaprao',
    name: 'Pad Kaprao',
    category: 'cat-prep',
    macroSource: 'derived',
    serves: 4,
    prepMinutes: 25,
    mealTypes: ['lunch', 'dinner'],
    batchFriendly: false,
    notes: 'youtube.com/shorts/a1zBLIJrGxM\n\nChilli at 28 g is the authentic heat; 12 g is medium. Servings not stated; four is an estimate for a pound of mince.',
    lines: [
      { foodId: 'fd-garlic', qty: 20, unit: 'g' },
      { foodId: 'fd-chili', qty: 28, unit: 'g' },
      { foodId: 'fd-vegoil', qty: 2, unit: 'tbsp' },
      { foodId: 'fd-beefmince', qty: 454, unit: 'g' },
      { foodId: 'fd-egg', qty: 1, unit: 'pcs' },
      { foodId: 'fd-fishsauce', qty: 12, unit: 'ml' },
      { foodId: 'fd-oystersauce', qty: 12, unit: 'ml' },
      { foodId: 'fd-soysauce', qty: 12, unit: 'ml' },
      { foodId: 'fd-darksoy', qty: 12, unit: 'ml' },
      { foodId: 'fd-sugar', qty: 4, unit: 'g' },
      { foodId: 'fd-msg', qty: 2, unit: 'g' },
      { foodId: 'fd-whitepepper', qty: 2, unit: 'g' },
      { foodId: 'fd-basil', qty: 20, unit: 'pcs' },
      { foodId: 'fd-mint', qty: 4, unit: 'pcs' },
      { foodId: 'fd-clove', qty: 0.25, unit: 'tsp' },
    ],
  },
];

export const libraryRecipes: Recipe[] = drafts.map((d) => {
  const withZero: Recipe = { ...d, macros: { ...ZERO_MACROS }, example: false };
  return { ...withZero, macros: recipeMacros(withZero, allFoods) };
});
